### ISSUE TITLE
安装到本地，登录链接http://localhost:3000/user/login失败

### ISSUE THREAD

**Issue by az031120103** [Jerry-web/my-account#2]
错误提示如下：
urserDao.js:135
    connecttion.query($sql.login,[...],function(){})
TypeError: cannot read property 'query' of undefined

应该是数据库链接错误，请问应该怎么链接数据库，初学不懂

**Comment by Jerry-web** [comment]
这个是数据库连接错误了，my-account/my-account-server/conf/db.js 目录下配置数据库

**Comment by az031120103** [comment]
搞定了，本地没安装mysql数据库

**Comment by Jerry-web** [comment]
哈哈哈，你也是做前端开发的啊？

**Comment by az031120103** [comment]
恩，做前端开发。

还有一个疑问，登录成功之后，主页调用的接口：http://localhost:3000/account/queryByMonthOrYear返回 {code:8} 是什么原因？

**Comment by Jerry-web** [comment]
code:8 表示未登录，登录node后台通过session记录登录状态，开发阶段将后台session判断部分去了就可以了。生产环境将前端npm run build 打包后放在server 的public就可以了

**Comment by Jerry-web** [comment]
code:8 表示未登录，登录node后台通过session记录登录状态，开发阶段将后台session判断部分去了就可以了。生产环境将前端npm run build 打包后放在server 的public就可以了
